
on: 
  workflow_dispatch:
  
name: 03-run-r-script

jobs: 
  write-message:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - name: print-message
        run: Rscript scripts/03-r-script.R
