
on: 
  workflow_dispatch:
  schedule:
    - cron: "*/4 * * * *"
  push: 
    branches:
      - main
      - master
  
name: 06-events

jobs: 
  write-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
            
      - name: print-message
        run: Rscript scripts/03-r-script.R
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
      
